---
- name: Install HTTP server conditionally for Ubuntu and Red Hat
  hosts: all
  become: yes
  tasks:
    - name: Install Apache on Ubuntu
      apt:
        name: apache2
        state: absent
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache on Red Hat
      yum:
        name: httpd
        state: absent
      when: ansible_distribution == "RedHat"

    - name: Start Apache service on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start Apache service on Red Hat
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "RedHat"
